### ISSUE TITLE
Cursor change

### ISSUE THREAD

**Issue by NeminiCedamus** [pdsimari/CubeQuest#15]
Because the mouse is now in charge of aiming, a part of the UI should be the aiming crosshair. From what I could read online, this is basically importing an image and then changing the cursor to be like it. I'll have the finished code for aiming tonight and then it could be changed once I commit that

**Comment by michaellmonaghan** [comment]
I'll take this one.

**Comment by michaellmonaghan** [comment]
Not sure this is required anymore. Feel free to reopen if you think it is.
