### ISSUE TITLE
Player Model

### ISSUE THREAD

**Issue by PashamAdwani** [pdsimari/CubeQuest#16]
Hello people!
As one of our suggested, I tried to pull up the character from Star-Wars . Houng and me,
![character](https://cloud.githubusercontent.com/assets/19986903/20368625/d7bf881a-ac22-11e6-9d95-5bb7bfe58e6d.PNG)
worked  a rough model.
Do you have any suggestions for the character?
Please let me know.

**Comment by PashamAdwani** [comment]
@NeminiCedamus 
what it this one?

**Comment by michaellmonaghan** [comment]
That looks great, nice work!

I don't have any suggestions at the moment other than perhaps some cylinders for the arms and legs.

**Comment by NeminiCedamus** [comment]
Could be a cool idea to have it have like wheels on the sides just so it's not getting into the standard "human" form. Also could make the game seem more "cartoonish" and fun

**Comment by PashamAdwani** [comment]
![walle](https://cloud.githubusercontent.com/assets/19986903/20726008/dc0af5de-b641-11e6-826f-508870322f81.PNG)
 what do u think of this?

**Comment by PashamAdwani** [comment]
@NeminiCedamus 
Check it out

**Comment by michaellmonaghan** [comment]
Awesome model! I reduced the polygon count and enabled smooth shading so things don't get choppy.
