### ISSUE TITLE
Potion Model

### ISSUE THREAD

**Issue by janlasota** [pdsimari/CubeQuest#17]

**Comment by janlasota** [comment]
![potion screenshot rough draft](https://cloud.githubusercontent.com/assets/23197984/20407480/947bd136-acdf-11e6-8cfe-cb4324490ae0.png)

What do y'all think of this?

**Comment by michaellmonaghan** [comment]
Looks great! Maybe make the cap a sphere instead of a hemisphere, its up to you.

**Comment by michaellmonaghan** [comment]
Nicely done!
